### PR TITLE
proposing a new redirect uri

### PR DESCRIPTION
**Pull request by jsun1**
I'm proposing to change the redirect URI to be `https://api.maltafinance.org/plaid` in the .env file (so that the URI contains "plaid"). This pull request shouldn't be merged, but rather the .env file in production should be updated with this new redirect URI. 

(I've already added this URI to the Plaid API dashboard at https://dashboard.plaid.com/team/api)

Along with this change, we also need the backend to add a static JSON file (not a redirect) at `https://api.maltafinance.org/.well-known/apple-app-site-association`. The contents of the json file should be:

```
{
    "applinks": {
        "details": [
            {
                "appIDs": [ "VAC259X872.org.candlelabs.malta-ios" ],
                "components": [
                    {
                        "/": "/plaid/*",
                        "comment": "Matches any URL path whose path starts with /plaid/"
                    }
                ]
            }
        ]
    }
}
```

This will enable certain banks in Plaid to properly redirect to the Malta app. More info here: https://plaid.com/docs/link/ios/
Priority: Take your time, as this is not a road blocker for now.

### CODE REVIEW

**Comment by jsun1** [comment]
cc @kiranmuddam @samisbakedham

**Comment by samisbakedham** [comment]
Should I update the QuickStart deployment?

**Comment by jsun1** [comment]
Yes thanks, the QuickStart deployment should have the .env updated to have `PLAID_REDIRECT_URI=https://api.maltafinance.org/plaid`

**Comment by jsun1** [comment]
Along with this change, we also need the backend to add a static JSON file (not a redirect) at this URL: https://api.maltafinance.org/.well-known/apple-app-site-association. The contents of the json file should be:

```
{
    "applinks": {
        "details": [
            {
                "appIDs": [ "VAC259X872.org.candlelabs.malta-ios" ],
                "components": [
                    {
                        "/": "/plaid/*",
                        "comment": "Matches any URL path whose path starts with /plaid/"
                    }
                ]
            }
        ]
    }
}
```

**Comment by samisbakedham** [comment]
Doing it now. Is the updated app on TestFlight? Maybe req for public beta access

**Comment by jsun1** [comment]
Thanks, I've updated it on TestFlight, and I'm looking into how to enable "public links" in TestFlight.

**Comment by samisbakedham** [comment]
> Thanks, I've updated it on TestFlight, and I'm looking into how to enable "public links" in TestFlight.

I'll set up public links

**Comment by jsun1** [comment]
Ok great thanks, do you see "External Testing" on the left-side under the TestFlight tab in App Store Connect? For me, I only see "Internal Testing" and I'm wondering if it's because of permissions/access level. I think public links would be configured there. 

Screen Shot 2022-08-23 at 6 04 40 PM

**Pull request merged**
